### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by dhearns** [beaston02/SMrecorder#3]
Getting this error after running the script for the first time in 3 days.  Could it be a configuration change on the site?

Traceback (most recent call last):
  File "SMRecorder.py", line 116, in <module>
    getOnlineModels()
  File "SMRecorder.py", line 45, in getOnlineModels
    online.append(model['Nickname'].lower())
AttributeError: 'NoneType' object has no attribute 'lower'

**Comment by beaston02** [comment]
Thank you for letting me know. I'll look into this when I get a chance.

**Comment by dhearns** [comment]
Script is working just fine now. So I'm assuming there was an issue with the site. I'll close the issue if it's still working a few hours from now.

**Comment by beaston02** [comment]
Thank you for reporting back. I'm glad it's back up and running!
