### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by forsomefun** [beaston02/SMrecorder#5]
Do you know what could be causing this output.  This is the first time this has happened. Not sure if it was a ram issue or something. 

> 3 model(s) are being recorded. Next check in 10 seconds
> ```
> Exception in thread Thread-904:recorded: ['oliviajaide', 'missquincam', 'carmitabonita']
> Traceback (most recent call last):
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\segmented.py", line 153, in run
>     result = future.result(timeout=0.5)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 405, in result
>     return self.__get_result()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 357, in __get_result
>     raise self._exception
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\hls.py", line 84, in fetch
>     **request_params)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\plugin\api\http_session.py", line 128, in request
>     *args, **kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 658, in send
>     r.content
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 823, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
> MemoryError
> 3 model(s) are being recorded. Next check in 8 seconds
> Exception in thread Thread-911:recorded: ['oliviajaide', 'missquincam', 'carmitabonita']
> Traceback (most recent call last):
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\segmented.py", line 153, in run
>     result = future.result(timeout=0.5)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 405, in result
>     return self.__get_result()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 357, in __get_result
>     raise self._exception
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\hls.py", line 84, in fetch
>     **request_params)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\plugin\api\http_session.py", line 128, in request
>     *args, **kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 658, in send
>     r.content
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 823, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
> MemoryError
> 3 model(s) are being recorded. Next check in 3 seconds
> Exception in thread Thread-881:recorded: ['oliviajaide', 'missquincam', 'carmitabonita']
> Traceback (most recent call last):
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
>     self.run()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\segmented.py", line 153, in run
>     result = future.result(timeout=0.5)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 405, in result
>     return self.__get_result()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\_base.py", line 357, in __get_result
>     raise self._exception
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\concurrent\futures\thread.py", line 55, in run
>     result = self.fn(*self.args, **self.kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\stream\hls.py", line 84, in fetch
>     **request_params)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 521, in get
>     return self.request('GET', url, **kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\livestreamer\plugin\api\http_session.py", line 128, in request
>     *args, **kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 508, in request
>     resp = self.send(prep, **send_kwargs)
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\sessions.py", line 658, in send
>     r.content
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests\models.py", line 823, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
> MemoryError
> Traceback (most recent call last):t check in 1 seconds
>   File "D:\Lockbox\Others\streammate\SMrecorder.py", line 116, in <module>
>     getOnlineModels()
>   File "D:\Lockbox\Others\streammate\SMrecorder.py", line 49, in getOnlineModels
>     thread.start()
>   File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 846, in start
>     _start_new_thread(self._bootstrap, ())
> RuntimeError: can't start new thread
> 
> ```

**Comment by beaston02** [comment]
I've never seen that before. I also wonder if it's an issue with system ram being available. Did you look at your systems resources by chance?

**Comment by forsomefun** [comment]
I switch to the 64bit version of python. 
It said AMD so it was confusing. 

But maybe that will help./

**Comment by beaston02** [comment]
I'm not sure if that will help, but it's worth a shot. 

For what it's worth, it's called "AMD64" because AMD was the first to develop the 64 bit system. I believe Intel has its own name for its 64 bit system, but "AMD64" is the name you always see even though it works on non AMD systems, so don't shy away from it because of the name AMD if you're running Intel

**Comment by forsomefun** [comment]
That will be good to know in the future.

Don't want to wasthe those extra GB
Thank yku

**Comment by beaston02** [comment]
Yeah, my network activity on here spiked like crazy, and I gained 500+ followers on here since then. 

Im going to go ahead and close this issue.
