### ISSUE TITLE
Some models aren't seen as being online

### ISSUE THREAD

**Issue by Houhie** [beaston02/SMrecorder#6]
I've noticed that some models aren't being seen as online even when they are. I'm not sure what the root cause is from a coding perspective, as I've only glanced momentarily at the code itself and it's been years since I've done anything in python anyways, but I notice it's with models that don't show up when you type their names in the search bar on any of the streamate-like sites. I did some brief googling and found that that can be caused by setting location visibility restrictions, and that if a model has any states or countries restricted then they also wont show up to free users when a search with their name is done. Presumably that's having some impact on the way this program sees users as online. I should note that free users can still view these pages if they type the url in directly instead of conducting a search using the built in features. Whether or not this is an easy fix I don't know, but I thought it's worth mentioning.

**Comment by beaston02** [comment]
Thank you for pointing this out. I had no idea this was the case! 

A quick solution would be creating a second list of models who are blocked (or what I'm going to refer to as "blocked" for lack of a better word). 

A better solution, which I'll see if I can code, is to have the script to check each model to see if it returns a result when searched on startup, or every so many hours. If they are not blocked, they will be monitored through the API system (current method), and if not, I'll have it check their profile page, or a the API directly for that model (I can't remember exactly how the code works off the top of my head). 

Do you by chance have a models name I could use as an example for this? If you would rather not discuss it in a public place, you can pm me on reddit (same username).

**Comment by Houhie** [comment]
Will do, I refrained from posting any specific names here just because I felt it was mildly inappropriate for a public setting.

**Comment by beaston02** [comment]
Thank you for communicating with me on reddit. I noticed the model you mentioned recorded on my end, so it looks like everything is good now!
